"use client";

import { useState } from "react";
import { buildNewsReviewPrompt } from "@/lib/news/prompt";
import { extractReviewFields } from "@/lib/news/parser";
import { emptyNewsAnswers, type NewsAnswers, type NewsDrillRecord } from "@/lib/news/types";
import { useNewsDrills } from "@/lib/news/use-news-drills";
import type { SourceContext } from "@/lib/vocabulary/types";
import { Arrow, Check, Clock } from "../icons";
import { CatalogVocabularyText } from "../vocabulary/catalog-text";

const sections: { key:keyof NewsAnswers; number:string; title:string; prompt:string; guide:string[] }[] = [
  { key:"retell", number:"01", title:"Retell", prompt:"What happened?", guide:["3–5 concise sentences","Use your own words","Separate fact from interpretation"] },
  { key:"whyItMatters", number:"02", title:"Why It Matters", prompt:"Why does this matter for markets?", guide:["Build the causal / transmission chain","Name intermediate variables","Challenge unsupported assumptions"] },
  { key:"riskView", number:"03", title:"Risk View", prompt:"What should a market-risk manager check?", guide:["Relevant exposures and P&L drivers","Material sensitivities, concentration, liquidity and hedging","Cross-asset stress, further checks and escalation"] },
  { key:"whatNext", number:"04", title:"What Next", prompt:"What would you watch next?", guide:["Choose relevant data, policy, market and positioning signals","Look for confirmation and invalidation","Avoid a headline-only watchlist"] },
];

type Props = { savedIds:Set<string>; onSaveTerm:(termId:string,context:SourceContext)=>void; onBack:()=>void };

export function NewsDrill({ savedIds, onSaveTerm, onBack }:Props) {
  const news = useNewsDrills();
  const [record,setRecord] = useState<NewsDrillRecord|null>(null); const [started,setStarted] = useState(false); const [copyStatus,setCopyStatus] = useState(""); const [reviewDraft,setReviewDraft] = useState(""); const [editingReview,setEditingReview] = useState(true); const [historyOpen,setHistoryOpen] = useState(true);
  const [input,setInput] = useState({headline:"",source:"",url:"",newsText:""});

  const start = () => { const now = new Date().toISOString(); const next:NewsDrillRecord = { id:crypto.randomUUID(), date:now, updatedAt:now, ...input, answers:{...emptyNewsAnswers}, copiedReviewPrompt:"", aiReview:"", extractedReview:{vocabularySuggestions:[]} }; setRecord(next); setStarted(true); setReviewDraft(""); setEditingReview(true); news.save(next); window.scrollTo({top:0,behavior:"smooth"}); };
  const updateRecord = (updater:(current:NewsDrillRecord)=>NewsDrillRecord) => setRecord((current) => current ? updater(current) : current);
  const updateAnswer = (key:keyof NewsAnswers,value:string) => updateRecord((current) => ({...current,answers:{...current.answers,[key]:value}}));
  const persist = (next:NewsDrillRecord) => { const saved = {...next,updatedAt:new Date().toISOString()}; setRecord(saved); news.save(saved); return saved; };
  const copyPrompt = async () => { if (!record) return; const prompt = buildNewsReviewPrompt(record); const saved = persist({...record,copiedReviewPrompt:prompt}); try { await navigator.clipboard.writeText(prompt); setCopyStatus("Copied — paste it into your preferred AI tool."); } catch { setCopyStatus("Prompt prepared. Select and copy it below."); } setRecord(saved); };
  const saveReview = () => { if (!record || !reviewDraft.trim()) return; persist({...record,aiReview:reviewDraft.trim(),extractedReview:extractReviewFields(reviewDraft)}); setEditingReview(false); };
  const reopen = (item:NewsDrillRecord) => { setRecord(item); setInput({headline:item.headline,source:item.source,url:item.url,newsText:item.newsText}); setReviewDraft(item.aiReview); setEditingReview(!item.aiReview); setStarted(true); setCopyStatus(""); window.scrollTo({top:0,behavior:"smooth"}); };
  const newDrill = () => { setRecord(null); setStarted(false); setInput({headline:"",source:"",url:"",newsText:""}); setReviewDraft(""); setCopyStatus(""); };
  const deleteReview = () => { if (!record) return; persist({...record,aiReview:"",extractedReview:{vocabularySuggestions:[]}}); setReviewDraft(""); setEditingReview(true); };

  return <section className="news-page"><header className="news-header"><button className="back" onClick={onBack}>← Dashboard</button><div><p className="kicker">MANUAL CURRENT-AFFAIRS PRACTICE</p><h1>News Drill</h1><p>Move from headline to transmission, risk, and the next signal.</p></div><button className="new-drill" onClick={newDrill}>+ New drill</button></header>
    {!started || !record ? <NewsInput input={input} setInput={setInput} onStart={start} /> : <div className="news-workspace"><aside className="news-source"><p className="category">SOURCE MATERIAL</p><h2>{record.headline}</h2><p className="source-line">{record.source || "Source not provided"}{record.url && <> · <a href={record.url} target="_blank" rel="noreferrer">Open link ↗</a></>}</p><div className="news-text"><CatalogVocabularyText text={record.newsText} context={{mode:"news",contentId:`${record.id}:news`,label:`News text: ${record.headline}`,surface:"news-text",excerpt:record.newsText.slice(0,300)}} savedIds={savedIds} onSave={onSaveTerm} /></div><p className="source-hint">Underlined catalog terms can be added to your Vocabulary Bank.</p></aside>
      <section className="news-exercise"><div className="workflow-line"><span className="active">News</span><i>→</i><span className="active">4 answers</span><i>→</i><span>AI review</span><i>→</i><span>Save</span></div>{sections.map((section) => <label className="news-section" key={section.key}><span className="news-number">{section.number}</span><span className="news-section-copy"><b>{section.title}</b><strong>{section.prompt}</strong><small>{section.guide.join(" · ")}</small></span><textarea rows={6} value={record.answers[section.key]} onChange={(event) => updateAnswer(section.key,event.target.value)} onBlur={() => news.save({...record,updatedAt:new Date().toISOString()})} placeholder="Write your view…" /></label>)}
        <section className="copy-review"><div><p className="category">EXTERNAL REVIEW</p><h2>Ready for a senior challenge?</h2><p>Copies the complete news, your four answers, and the evaluation rubric. No API call is made.</p></div><button className="copy-ai" onClick={copyPrompt} disabled={!allAnswersComplete(record.answers)}>Copy for AI Review <Arrow /></button>{copyStatus && <p className="copy-status"><Check /> {copyStatus}</p>}{record.copiedReviewPrompt && <details><summary>Preview copied prompt</summary><pre>{record.copiedReviewPrompt}</pre></details>}</section>
        <section className="paste-review"><p className="category">PASTE AI REVIEW</p>{editingReview || !record.aiReview ? <><h2>Bring the feedback back.</h2><textarea className="review-textarea" rows={14} value={reviewDraft} onChange={(event) => setReviewDraft(event.target.value)} placeholder="Paste the complete external AI review here…" /><button className="primary" disabled={!reviewDraft.trim()} onClick={saveReview}>Save Review <Arrow /></button></> : <SavedReview record={record} savedIds={savedIds} onSaveTerm={onSaveTerm} onEdit={() => setEditingReview(true)} onReplace={() => { setReviewDraft(""); setEditingReview(true); }} onCopy={async () => { await navigator.clipboard.writeText(record.aiReview); setCopyStatus("Review copied."); }} onDelete={deleteReview} />}</section>
      </section></div>}
    <NewsHistory records={news.records} hydrated={news.hydrated} open={historyOpen} setOpen={setHistoryOpen} onReopen={reopen} onDelete={(id) => { news.remove(id); if (record?.id === id) newDrill(); }} activeId={record?.id} />
  </section>;
}

function NewsInput({ input,setInput,onStart }: { input:{headline:string;source:string;url:string;newsText:string}; setInput:(value:{headline:string;source:string;url:string;newsText:string})=>void; onStart:()=>void }) {
  return <div className="news-input"><div><p className="category">STEP 01 / INPUT</p><h2>Paste one story.<br />Interrogate the risk.</h2><p>No feed, scraping, or automatic retrieval. Use the source material you choose.</p></div><form onSubmit={(event) => {event.preventDefault();onStart();}}><label><span>Headline *</span><input value={input.headline} onChange={(event) => setInput({...input,headline:event.target.value})} placeholder="What is the story?" /></label><div className="input-split"><label><span>Source</span><input value={input.source} onChange={(event) => setInput({...input,source:event.target.value})} placeholder="Optional" /></label><label><span>URL</span><input type="url" value={input.url} onChange={(event) => setInput({...input,url:event.target.value})} placeholder="https://…" /></label></div><label><span>News / article text or summary *</span><textarea rows={12} value={input.newsText} onChange={(event) => setInput({...input,newsText:event.target.value})} placeholder="Paste the relevant article text or your source summary…" /></label><button className="primary" disabled={!input.headline.trim() || !input.newsText.trim()}>Start Drill <Arrow /></button></form></div>;
}

function SavedReview({ record,savedIds,onSaveTerm,onEdit,onReplace,onCopy,onDelete }: { record:NewsDrillRecord;savedIds:Set<string>;onSaveTerm:(termId:string,context:SourceContext)=>void;onEdit:()=>void;onReplace:()=>void;onCopy:()=>void;onDelete:()=>void }) {
  const extracted = record.extractedReview;
  return <div className="saved-review"><div className="review-title"><div><p className="category">SAVED REVIEW</p><h2>{extracted.overallScore !== undefined ? `${extracted.overallScore}/100` : "External feedback"}</h2></div><div><button onClick={onEdit}>Edit</button><button onClick={onReplace}>Replace</button><button onClick={onCopy}>Copy</button><button onClick={onDelete}>Delete review</button></div></div>{(extracted.biggestGap || extracted.lesson) && <div className="review-extract">{extracted.biggestGap && <p><span>BIGGEST GAP</span>{extracted.biggestGap}</p>}{extracted.lesson && <p><span>ONE-SENTENCE LESSON</span>{extracted.lesson}</p>}</div>}<div className="raw-review"><CatalogVocabularyText text={record.aiReview} context={{mode:"news",contentId:`${record.id}:review`,label:`News AI review: ${record.headline}`,surface:"ai-review",excerpt:record.aiReview.slice(0,300)}} savedIds={savedIds} onSave={onSaveTerm} /></div>{extracted.vocabularySuggestions.length > 0 && <div className="review-vocabulary"><span>VOCABULARY SUGGESTIONS</span>{extracted.vocabularySuggestions.map((item,index) => <p key={`${item}-${index}`}><CatalogVocabularyText text={item} context={{mode:"news",contentId:`${record.id}:review-vocabulary:${index}`,label:`News AI review vocabulary: ${record.headline}`,surface:"ai-review",excerpt:item}} savedIds={savedIds} onSave={onSaveTerm} /></p>)}</div>}</div>;
}

function NewsHistory({ records,hydrated,open,setOpen,onReopen,onDelete,activeId }: { records:NewsDrillRecord[];hydrated:boolean;open:boolean;setOpen:(value:boolean)=>void;onReopen:(record:NewsDrillRecord)=>void;onDelete:(id:string)=>void;activeId?:string }) {
  return <section className="news-history"><button className="history-toggle" onClick={() => setOpen(!open)}><span><Clock /> NEWS HISTORY <b>{hydrated ? records.length : 0}</b></span><span>{open ? "−" : "+"}</span></button>{open && <div className="history-list">{records.length ? records.map((record) => <article className={activeId === record.id ? "active" : ""} key={record.id}><div><span>{formatDate(record.date)}</span><h3>{record.headline}</h3><p>{record.source || "No source"} · {record.aiReview ? "Review saved" : record.copiedReviewPrompt ? "Prompt copied" : "In progress"}</p></div><div><button onClick={() => onReopen(record)}>Reopen <Arrow /></button><button onClick={() => onDelete(record.id)}>Delete</button></div></article>) : <p className="history-empty">Completed and in-progress drills will appear here.</p>}</div>}</section>;
}

function allAnswersComplete(answers:NewsAnswers) { return Object.values(answers).every((answer) => answer.trim().length >= 10); }
function formatDate(value:string) { return new Intl.DateTimeFormat("en",{year:"numeric",month:"short",day:"numeric"}).format(new Date(value)); }
