import type { VocabularyTerm } from "./types";

export const vocabularyCatalog: VocabularyTerm[] = [
  { id:"real-yield", term:"Real yield", aliases:["real yields"], category:"Rates", definitionEn:"A bond yield adjusted for expected inflation.", definitionZh:"扣除预期通胀后的债券收益率。", definitionJa:"予想インフレ率を差し引いた債券利回り。", practicalExplanation:"It is the market’s inflation-adjusted cost of money and a key discount rate for assets.", exampleEn:"Higher real yields pressured long-duration equities.", exampleJa:"実質利回りの上昇が長期デュレーション株を圧迫した。" },
  { id:"inflation-expectations", term:"Inflation expectations", category:"Macro", definitionEn:"The rate of future inflation expected by markets or households.", definitionZh:"市场或家庭对未来通胀率的预期。", definitionJa:"市場や家計が予想する将来のインフレ率。", practicalExplanation:"Markets separate nominal yields into expected inflation and a real return.", exampleEn:"Inflation expectations rose after the oil shock.", exampleJa:"原油ショック後、インフレ期待が上昇した。" },
  { id:"long-duration", term:"Long-duration asset", aliases:["long-duration growth stocks"], category:"Risk Management", definitionEn:"An asset whose value depends heavily on cash flows far in the future.", definitionZh:"价值高度依赖遥远未来现金流的资产。", definitionJa:"遠い将来のキャッシュフローに価値が大きく依存する資産。", practicalExplanation:"When discount rates rise, distant cash flows lose more present value.", exampleEn:"Software stocks often behave like long-duration assets.", exampleJa:"ソフトウェア株は長期デュレーション資産のように動くことが多い。" },
  { id:"carry-trade", term:"Carry trade", aliases:["yen-funded carry trades"], category:"FX", definitionEn:"Borrowing in a low-yielding currency to invest in a higher-yielding asset.", definitionZh:"借入低收益货币并投资于高收益资产的交易。", definitionJa:"低金利通貨で借り、高利回り資産に投資する取引。", practicalExplanation:"The trade earns the rate difference but can unwind violently when the funding currency rises.", exampleEn:"A stronger yen forced investors to unwind carry trades.", exampleJa:"円高により投資家はキャリートレードの巻き戻しを迫られた。" },
  { id:"deleveraging", term:"Deleveraging", category:"Risk Management", definitionEn:"Reducing borrowed exposure by selling assets or repaying debt.", definitionZh:"通过出售资产或偿还债务来降低杠杆。", definitionJa:"資産売却や債務返済によってレバレッジを下げること。", practicalExplanation:"When losses rise, leveraged investors may have to sell even if prices already look cheap.", exampleEn:"Margin calls triggered cross-asset deleveraging.", exampleJa:"マージンコールがクロスアセットのデレバレッジを引き起こした。" },
  { id:"supply-shock", term:"Supply shock", category:"Macro", definitionEn:"A sudden change in the availability or cost of goods or productive inputs.", definitionZh:"商品或生产要素的供应量或成本突然变化。", definitionJa:"財や生産投入の供給量・コストが急変すること。", practicalExplanation:"A negative supply shock can raise prices while weakening growth at the same time.", exampleEn:"The shipping disruption created an energy supply shock.", exampleJa:"航路の寸断がエネルギー供給ショックを生んだ。" },
  { id:"terms-of-trade", term:"Terms of trade", category:"Macro", definitionEn:"The ratio of a country’s export prices to its import prices.", definitionZh:"一国出口价格与进口价格的比率。", definitionJa:"一国の輸出価格を輸入価格で割った比率。", practicalExplanation:"If imported energy becomes dearer, an importing country must give up more exports to buy it.", exampleEn:"Higher oil prices worsened the importer’s terms of trade.", exampleJa:"原油高は輸入国の交易条件を悪化させた。" },
  { id:"current-account", term:"Current account", aliases:["current account balance"], category:"Macro", definitionEn:"A country’s balance of trade, income, and current transfers with the rest of the world.", definitionZh:"一国与世界其他地区之间的贸易、收入和经常转移收支。", definitionJa:"貿易・所得・経常移転を含む対外収支。", practicalExplanation:"A bigger import bill usually weakens it unless exports or foreign income rise too.", exampleEn:"The energy bill pushed the current account into deficit.", exampleJa:"エネルギー輸入額の増加で経常収支は赤字に転じた。" },
  { id:"bull-steepening", term:"Bull steepening", aliases:["bull-steepens"], category:"Rates", definitionEn:"A yield-curve steepening caused by short-term yields falling faster than long-term yields.", definitionZh:"短期收益率下降快于长期收益率所导致的收益率曲线变陡。", definitionJa:"短期金利が長期金利より速く低下して起きるイールドカーブのスティープ化。", practicalExplanation:"Bond prices rise overall, while markets price faster policy easing at the front end.", exampleEn:"Weak payrolls caused a bull steepening in Treasuries.", exampleJa:"弱い雇用統計で米国債はブル・スティープ化した。" },
  { id:"bear-steepening", term:"Bear steepening", aliases:["bear-steepens"], category:"Rates", definitionEn:"A yield-curve steepening caused by long-term yields rising faster than short-term yields.", definitionZh:"长期收益率上升快于短期收益率所导致的收益率曲线变陡。", definitionJa:"長期金利が短期金利より速く上昇して起きるイールドカーブのスティープ化。", practicalExplanation:"Bond prices fall, especially at the long end, often on inflation, supply, or term-premium concerns.", exampleEn:"The inflation shock produced a bear steepening.", exampleJa:"インフレショックでベア・スティープ化が進んだ。" },
  { id:"yield-curve", term:"Yield curve", category:"Rates", definitionEn:"A line showing bond yields across different maturities for the same borrower.", definitionZh:"显示同一借款人在不同期限上的债券收益率曲线。", definitionJa:"同一発行体の満期別利回りを結んだ曲線。", practicalExplanation:"Its shape summarizes expectations for policy, growth, inflation, and term premium.", exampleEn:"The yield curve steepened after the policy surprise.", exampleJa:"政策サプライズ後、イールドカーブはスティープ化した。" },
  { id:"credit-spread", term:"Credit spread", aliases:["credit spreads"], category:"Credit", definitionEn:"The extra yield a risky bond offers over a comparable government bond.", definitionZh:"风险债券相对于可比政府债券提供的额外收益率。", definitionJa:"リスクのある債券が同年限の国債に上乗せする利回り。", practicalExplanation:"It is the market price of default, liquidity, and uncertainty in corporate debt.", exampleEn:"Credit spreads widened as default concerns increased.", exampleJa:"デフォルト懸念の高まりでクレジットスプレッドが拡大した。" },
  { id:"basis-point", term:"Basis point", aliases:["bp"], category:"Rates", definitionEn:"One hundredth of one percentage point, or 0.01%.", definitionZh:"一个百分点的百分之一，即0.01%。", definitionJa:"1パーセントポイントの100分の1、すなわち0.01%。", practicalExplanation:"A 25bp rate increase means a move from 4.00% to 4.25%.", exampleEn:"Two-year yields rose 18 basis points.", exampleJa:"2年債利回りは18ベーシスポイント上昇した。" },
  { id:"policy-divergence", term:"Policy divergence", category:"Macro", definitionEn:"A widening difference between the monetary-policy paths of two economies.", definitionZh:"两个经济体货币政策路径之间的差异扩大。", definitionJa:"二つの経済圏の金融政策経路の乖離が広がること。", practicalExplanation:"Different expected interest rates can redirect capital and move exchange rates.", exampleEn:"Policy divergence supported the euro against the yen.", exampleJa:"金融政策の乖離がユーロの対円上昇を支えた。" },
  { id:"investment-grade", term:"Investment-grade bond", aliases:["investment-grade property bonds"], category:"Credit", definitionEn:"A bond rated BBB-/Baa3 or higher by major rating agencies.", definitionZh:"主要评级机构评为BBB-/Baa3或以上的债券。", definitionJa:"主要格付会社でBBB-/Baa3以上に格付けされた債券。", practicalExplanation:"It has lower expected default risk than high yield, but can still lose money when rates or spreads rise.", exampleEn:"Investment-grade bonds sold off as yields rose.", exampleJa:"利回り上昇で投資適格債が売られた。" },
  { id:"high-yield", term:"High-yield bond", aliases:["high-yield energy bonds"], category:"Credit", definitionEn:"A bond below investment grade that pays more yield for higher credit risk.", definitionZh:"低于投资级、因信用风险较高而提供更高收益率的债券。", definitionJa:"投資適格未満で、高い信用リスクの対価として高利回りを提供する債券。", practicalExplanation:"Its price often responds more to business health and spreads than to government yields alone.", exampleEn:"High-yield energy bonds rallied with oil prices.", exampleJa:"ハイイールドのエネルギー債は原油高とともに上昇した。" },
  { id:"inflation-swap", term:"5y5y inflation swap", aliases:["5y5y inflation swaps"], category:"Rates", definitionEn:"A market measure of expected five-year inflation beginning five years from now.", definitionZh:"市场对五年后开始的未来五年通胀率的衡量。", definitionJa:"5年後から始まる5年間の予想インフレ率を示す市場指標。", practicalExplanation:"It looks beyond near-term noise to show perceived medium-to-long-term inflation risk.", exampleEn:"The 5y5y inflation swap rose after the commodity shock.", exampleJa:"商品ショック後、5年先5年インフレスワップが上昇した。" },
  { id:"receive-fixed", term:"Receive fixed", aliases:["receives fixed"], category:"Rates", definitionEn:"A swap position that receives a fixed interest rate and pays a floating rate.", definitionZh:"在利率互换中收取固定利率并支付浮动利率的头寸。", definitionJa:"金利スワップで固定金利を受け取り、変動金利を支払うポジション。", practicalExplanation:"It generally gains when market swap rates fall and loses when they rise.", exampleEn:"The receive-fixed position lost value as long-term rates climbed.", exampleJa:"長期金利の上昇で固定受けポジションは損失を出した。" },
  { id:"short-position", term:"Short position", aliases:["short CAD position"], category:"Risk Management", definitionEn:"A position that benefits when the price of an asset or currency falls.", definitionZh:"当资产或货币价格下跌时获利的头寸。", definitionJa:"資産や通貨の価格下落で利益が出るポジション。", practicalExplanation:"Being short CAD means losing if the Canadian dollar strengthens.", exampleEn:"The short CAD position was hurt by higher oil prices.", exampleJa:"原油高でCADショートポジションは損失を被った。" },
  { id:"pnl-driver", term:"P&L driver", aliases:["P&L drivers"], category:"Risk Management", definitionEn:"A market factor or position characteristic that causes profit or loss.", definitionZh:"导致盈利或亏损的市场因素或头寸特征。", definitionJa:"損益を生み出す市場要因またはポジション特性。", practicalExplanation:"Naming the driver links a market move to the portfolio instead of merely describing prices.", exampleEn:"Rates and FX were the main P&L drivers.", exampleJa:"金利と為替が主な損益要因だった。" },
  { id:"discount-rate", term:"Discount rate", aliases:["discount rates"], category:"Risk Management", definitionEn:"The rate used to convert future cash flows into present value.", definitionZh:"将未来现金流折算为现值所使用的利率。", definitionJa:"将来のキャッシュフローを現在価値に換算するための利率。", practicalExplanation:"A higher discount rate makes future profits worth less today, especially for long-duration assets.", exampleEn:"A higher discount rate reduced the valuation of growth stocks.", exampleJa:"割引率の上昇で成長株の評価額が低下した。" },
  { id:"inflation-breakeven", term:"Inflation breakeven", aliases:["inflation breakevens"], category:"Rates", definitionEn:"The inflation rate at which nominal and inflation-linked government bonds provide the same return.", definitionZh:"使名义国债与通胀挂钩国债回报相同的通胀率。", definitionJa:"名目国債と物価連動国債の収益率が等しくなるインフレ率。", practicalExplanation:"It is a market-based gauge of expected inflation plus inflation risk and liquidity effects.", exampleEn:"Oil prices pushed inflation breakevens higher.", exampleJa:"原油高でブレークイーブン・インフレ率が上昇した。" },
  { id:"floating-rate", term:"Floating-rate asset", aliases:["Floating-rate banks","floating rate"], category:"Rates", definitionEn:"An asset or exposure whose interest payment resets with a reference rate.", definitionZh:"利息支付随参考利率重设的资产或敞口。", definitionJa:"基準金利に連動して利払いが見直される資産またはエクスポージャー。", practicalExplanation:"Its income can rise when short-term rates reset higher, though funding and credit still matter.", exampleEn:"Floating-rate assets benefited from higher policy rates.", exampleJa:"変動金利資産は政策金利の上昇から恩恵を受けた。" },
  { id:"default-risk", term:"Default risk", aliases:["default concerns","credit risk"], category:"Credit", definitionEn:"The risk that a borrower cannot make promised interest or principal payments.", definitionZh:"借款人无法按约支付利息或本金的风险。", definitionJa:"借り手が約束した利息や元本を支払えなくなるリスク。", practicalExplanation:"Investors demand wider credit spreads when they think repayment has become less certain.", exampleEn:"Default risk increased as corporate cash flow weakened.", exampleJa:"企業キャッシュフローの悪化でデフォルトリスクが高まった。" },
  { id:"funding-cost", term:"Funding cost", aliases:["funding cost","funding conditions"], category:"Risk Management", definitionEn:"The interest rate or total expense paid to finance a position or business.", definitionZh:"为头寸或业务融资所支付的利率或总成本。", definitionJa:"ポジションや事業の資金調達に支払う金利または総コスト。", practicalExplanation:"A trade can lose even when the asset is stable if the cost of borrowing rises sharply.", exampleEn:"Yen strength increased the carry trade’s funding cost.", exampleJa:"円高でキャリートレードの資金調達コストが上昇した。" },
];

export const vocabularyById = new Map(vocabularyCatalog.map((term) => [term.id, term]));
