"use client";

import { useDeferredValue, useMemo, useState } from "react";
import { vocabularyById, vocabularyCatalog } from "@/lib/vocabulary/catalog";
import { contentOverridesFrom } from "@/lib/vocabulary/content";
import { isUnmastered, prioritizedEntries } from "@/lib/vocabulary/scheduler";
import { vocabularyCategories, type ReviewResult, type VocabularyCategory, type VocabularyContentOverrides, type VocabularyEntry, type VocabularyTerm } from "@/lib/vocabulary/types";
import { Arrow, Clock } from "../icons";
import { useVocabularyContent } from "./content-context";
import { VocabularyReview, type ReviewMode } from "./vocabulary-review";

type Props = { entries:VocabularyEntry[]; onRemove:(termId:string)=>void; onReview:(termId:string,result:ReviewResult)=>void; onUpdateContent:(termId:string,overrides:VocabularyContentOverrides)=>void; onResetContent:(termId:string)=>void; onBack:()=>void };
type Filter = "All" | VocabularyCategory | "Difficult / Unmastered";

export function VocabularyBank({ entries, onRemove, onReview, onUpdateContent, onResetContent, onBack }: Props) {
  const { getTerm } = useVocabularyContent();
  const [search, setSearch] = useState(""); const deferredSearch = useDeferredValue(search); const [filter, setFilter] = useState<Filter>("All"); const [reviewMode, setReviewMode] = useState<ReviewMode | null>(null); const [expanded, setExpanded] = useState<string | null>(null); const [editing, setEditing] = useState<string | null>(null);
  const queue = useMemo(() => prioritizedEntries(entries), [entries]);
  const filtered = useMemo(() => {
    const query = deferredSearch.trim().toLocaleLowerCase();
    return entries.flatMap((entry) => { const term = getTerm(entry.termId); if (!term) return []; const matchesFilter = filter === "All" || filter === "Difficult / Unmastered" ? filter === "All" || isUnmastered(entry) : term.category === filter; const haystack = `${term.term} ${term.definitionEn} ${term.definitionZh} ${term.definitionJa} ${term.practicalExplanation} ${term.exampleEn} ${term.exampleJa}`.toLocaleLowerCase(); return matchesFilter && (!query || haystack.includes(query)) ? [{entry,term}] : []; }).toSorted((a,b) => a.term.term.localeCompare(b.term.term));
  }, [entries, deferredSearch, filter, getTerm]);

  if (reviewMode) return <VocabularyReview entries={queue} mode={reviewMode} onReview={onReview} onExit={() => setReviewMode(null)} />;
  return <section className="vocabulary-page"><header className="vocabulary-hero"><button className="back" onClick={onBack}>← Dashboard</button><div><p className="kicker">PERSONAL LEARNING LAYER</p><h1>Vocabulary Bank</h1><p>Keep the language that helps you see risk faster.</p></div><div className="vocab-stat"><strong>{entries.length}</strong><span>SAVED TERMS</span></div></header>
    <div className="review-launch"><div><p className="category">SMART REVIEW</p><h2>{entries.length ? `${queue.filter((entry) => new Date(entry.review.nextReviewAt) <= new Date()).length || Math.min(5, entries.length)} terms ready to strengthen.` : "Your first review starts with one saved term."}</h2><p>Difficult and previously missed terms appear first.</p></div><div className="review-mode-buttons">{(["flashcard","multiple-choice","en-recall","asian-recall"] as ReviewMode[]).map((mode) => <button key={mode} disabled={!entries.length} onClick={() => setReviewMode(mode)}>{reviewModeLabel(mode)} <Arrow /></button>)}</div></div>
    <div className="vocab-tools"><label><span>SEARCH</span><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Term or definition…" /></label><div className="filter-row" aria-label="Vocabulary filters">{(["All",...vocabularyCategories,"Difficult / Unmastered"] as Filter[]).map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div></div>
    {filtered.length ? <div className="vocab-list">{filtered.map(({entry,term}) => { const isOpen = expanded === entry.termId; const isEditing = editing === entry.termId; return <article className={`vocab-entry ${isOpen ? "open" : ""}`} key={entry.termId}><button className="vocab-entry-summary" onClick={() => { setExpanded(isOpen ? null : entry.termId); if (isOpen) setEditing(null); }}><span className="term-category">{term.category}</span><span><strong>{term.term}</strong><small>{term.definitionEn}</small></span><span className={`status status-${entry.review.status}`}>{entry.review.status}</span><span className="entry-toggle">{isOpen ? "−" : "+"}</span></button>{isOpen && <div className="vocab-entry-detail">{isEditing ? <VocabularyEditForm defaultTerm={vocabularyById.get(entry.termId)!} term={term} hasOverrides={Boolean(entry.contentOverrides && Object.keys(entry.contentOverrides).length)} onSave={(edited) => { onUpdateContent(entry.termId,contentOverridesFrom(vocabularyById.get(entry.termId)!,edited)); setEditing(null); }} onCancel={() => setEditing(null)} onReset={() => { onResetContent(entry.termId); setEditing(null); }} /> : <><div className="entry-content-actions"><button onClick={() => setEditing(entry.termId)}>Edit</button>{entry.contentOverrides && Object.keys(entry.contentOverrides).length > 0 && <span>Personalized</span>}</div><div className="definition-grid"><p><span>ENGLISH</span>{term.definitionEn}</p><p><span>中文</span>{term.definitionZh}</p><p><span>日本語</span>{term.definitionJa}</p></div><p className="practical"><b>IN PRACTICE</b>{term.practicalExplanation}</p><div className="example-grid"><p><span>EXAMPLE / EN</span>{term.exampleEn}</p><p><span>例文 / 日本語</span>{term.exampleJa}</p></div><div className="entry-history"><p><Clock /> Added {formatDate(entry.dateAdded)} · Reviewed {entry.review.reviewCount}× · {entry.review.correctCount} correct / {entry.review.incorrectCount} incorrect · Difficulty {entry.review.difficulty}/5</p><p>Found in: {entry.sourceContexts.map((context) => context.label).join(", ")}</p><button onClick={() => onRemove(entry.termId)}>Remove</button></div></>}</div>}</article>; })}</div> : <div className="vocab-empty"><span>V</span><h2>{entries.length ? "No terms match this view." : "Your bank is ready."}</h2><p>{entries.length ? "Try a broader search or another category." : `Click an underlined term in Busy, Normal, or Deep mode, then choose “Add to Vocabulary.” ${vocabularyCatalog.length} starter concepts are available across the current exercises.`}</p></div>}
  </section>;
}

function VocabularyEditForm({ defaultTerm, term, hasOverrides, onSave, onCancel, onReset }: { defaultTerm:VocabularyTerm; term:VocabularyTerm; hasOverrides:boolean; onSave:(term:VocabularyTerm)=>void; onCancel:()=>void; onReset:()=>void }) {
  const [draft,setDraft] = useState(term);
  const update = <K extends keyof VocabularyTerm>(field:K,value:VocabularyTerm[K]) => setDraft((current) => ({...current,[field]:value}));
  const submit = (event:React.FormEvent) => { event.preventDefault(); onSave({...draft,term:draft.term.trim(),definitionEn:draft.definitionEn.trim(),definitionZh:draft.definitionZh.trim(),definitionJa:draft.definitionJa.trim(),practicalExplanation:draft.practicalExplanation.trim(),exampleEn:draft.exampleEn.trim(),exampleJa:draft.exampleJa.trim()}); };
  return <form className="vocab-edit-form" onSubmit={submit}><div className="edit-form-head"><div><p className="category">EDIT SAVED CONTENT</p><h3>{defaultTerm.term}</h3></div><span>Defaults remain unchanged.</span></div><label><span>TERM</span><input required value={draft.term} onChange={(event) => update("term",event.target.value)} /></label><div className="edit-definition-grid"><label><span>ENGLISH DEFINITION</span><textarea required rows={4} value={draft.definitionEn} onChange={(event) => update("definitionEn",event.target.value)} /></label><label><span>CHINESE DEFINITION</span><textarea required rows={4} value={draft.definitionZh} onChange={(event) => update("definitionZh",event.target.value)} /></label><label><span>JAPANESE DEFINITION</span><textarea required rows={4} value={draft.definitionJa} onChange={(event) => update("definitionJa",event.target.value)} /></label></div><label><span>PRACTICAL EXPLANATION</span><textarea required rows={3} value={draft.practicalExplanation} onChange={(event) => update("practicalExplanation",event.target.value)} /></label><div className="edit-example-grid"><label><span>ENGLISH EXAMPLE</span><textarea required rows={3} value={draft.exampleEn} onChange={(event) => update("exampleEn",event.target.value)} /></label><label><span>JAPANESE EXAMPLE</span><textarea required rows={3} value={draft.exampleJa} onChange={(event) => update("exampleJa",event.target.value)} /></label></div><label><span>CATEGORY</span><select value={draft.category} onChange={(event) => update("category",event.target.value as VocabularyCategory)}>{vocabularyCategories.map((category) => <option key={category}>{category}</option>)}</select></label><div className="edit-actions"><button type="button" className="text-button" disabled={!hasOverrides} onClick={onReset}>Reset to default</button><span /><button type="button" className="text-button" onClick={onCancel}>Cancel</button><button className="primary">Save</button></div></form>;
}

function reviewModeLabel(mode: ReviewMode) { return ({ flashcard:"Flashcards", "multiple-choice":"Meaning quiz", "en-recall":"EN → CN / JP", "asian-recall":"CN / JP → EN" })[mode]; }
function formatDate(value:string) { return new Intl.DateTimeFormat("en",{year:"numeric",month:"short",day:"numeric"}).format(new Date(value)); }
